import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'path'
import compression from 'vite-plugin-compression'

/**
 * Vite configuration with optimized code splitting for production builds.
 *
 * Chunk Strategy (gzipped sizes from build report):
 * - naive-ui: ~68KB - largest dep, separate for long-term caching
 * - canvas: ~54KB - Canvas.vue + composables + stores + utils
 * - vendor: ~2KB - VueUse, Lucide icons, Pinia (merged into one chunk)
 * - Dialog/Panel chunks: lazy-loaded on demand (~15KB total)
 * - initial total: ~140KB gzipped (well under 500KB target)
 *
 * Compression: gzip (vite-plugin-compression, threshold=3KB) + brotli (scripts/generate-brotli.mjs)
 * - threshold=3KB avoids compressing tiny chunks (HTTP overhead > savings for <3KB)
 * - brotli achieves ~30% better compression than gzip on JS/CSS
 * - both formats served automatically via content negotiation (nginx `gzip_static on; br_static on`)
 *
 * Note on composables chunk splitting:
 * Canvas composables are bundled into canvas.js (not split further) because:
 * 1. They are only imported by Canvas.vue (no cross-entry reuse)
 * 2. Vite/Rollup only creates separate chunks for modules used by multiple
 *    entry points OR via dynamic imports
 * 3. The barrel file (composables/index.ts) is inlined, not a separate chunk
 */
export default defineConfig({
  plugins: [
    vue(),
    compression({
      algorithm: 'gzip',
      ext: '.gz',
      // 3KB threshold: tiny chunks don't benefit from compression
      // (decompression overhead ≈ transfer savings for <3KB files)
      threshold: 3000,
    }),
    // Brotli (.br) files are generated by scripts/generate-brotli.mjs
    // (runs automatically after vite build via package.json script)
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 5173,
    host: true,
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    target: 'es2020',
    cssCodeSplit: true,
    // Enable verbose build reporting
    reportCompressedSize: true,
    chunkSizeWarningLimit: 500, // KB - warn only, not error
    rollupOptions: {
      output: {
        // Consistent chunk naming for better caching
        manualChunks(id) {
          // Normalize path separators for cross-platform comparison
          const n = id.replace(/\\/g, '/')

          // === External dependencies (node_modules) ===
          if (id.includes('node_modules')) {
            // Naive UI - largest external dep, separate for long-term caching
            if (id.includes('naive-ui') || id.includes('naive')) return 'naive-ui'
            // Vue core runtime
            if (id.includes('vue/dist/vue.runtime.esm-bundler')) return 'vue'
            // Vendor: Pinia, VueUse, Lucide
            if (id.includes('pinia')) return 'vendor'
            if (id.includes('@vueuse') || id.includes('lucide')) return 'vendor'
            return // let Vite handle remaining node_modules
          }

          // === src/ modules ===
          // Canvas main component → separate chunk for better caching
          if (n.endsWith('Canvas.vue')) return 'canvas'
        },
        // Asset file naming
        assetFileNames: (assetInfo) => {
          const info = assetInfo.name || ''
          // Keep readable names for CSS
          if (info.endsWith('.css')) {
            return 'assets/[name]-[hash][extname]'
          }
          return 'assets/[name]-[hash][extname]'
        },
        // Chunk file naming
        chunkFileNames: 'assets/[name]-[hash].js',
      },
    },
    // Minification is esbuild by default
  },
})
